### ISSUE TITLE
Implement guideline F6: Use start events only in initial fragments

### ISSUE THREAD

**Issue by ma-ro** [bptlab/fCM-design-support#102]
Check the number of start events

--> more than 1 : warning
--> less than 1: error

- [x] warning & error are displayed in error table
- [x] warn/inform when more than one start event
- [x] error when no start event
- [x] error when start fragment does not create the case class
- [ ] Quick fix: Create case-class-creating reference
- [x] oushed to develop

**Comment by kerstinandree** [comment]
Do we already check if the case object is created in each start fragment?
