### ISSUE TITLE
How to notify users for non-fulfilled guidelines

### ISSUE THREAD

**Issue by kerstinandree** [bptlab/fCM-design-support#14]
Discuss how we can notify a user if guidelines are not fulfilled. Think about a user-friendly way.

**Comment by LeonBein** [comment]
@kerstinandree is this task fulfilled? Does it collide with #58 ?

**Comment by kerstinandree** [comment]
No, it is not fulfilled. Furthermore, I think the task you referred is not meant to be solved by developers since it is a research question and we first need to check literature for answering the question about how to design an error message. @carlaterboven and I plan to do some research about that next time we meet, but you can also have a look at following papers listed below if the task is one of your urgent ones. I also think that we need to discuss the design next Wednesday if possible that you can include it in the tool. 

- https://dl.acm.org/doi/pdf/10.1145/3290607.3312978?casa_token=7CsjEcCBgkQAAAAA:Q9HLAzZ-iP7cvZFC5XlEZImIrsKDsZjAUdbXBNsmwthmmPf20UGkxOUy-Z8beu2ZjFzBrXXvPJPt
- https://dl.acm.org/doi/pdf/10.1145/2163.358083?casa_token=7aAiu3RwPUYAAAAA:bYZTjMl8jyj8dXoS65WLZDi4p_a7AMl5XIhWgL5btXtuG8cfL99IFW4ghnEeWaBCzTf932vbTWXO
- There is also a book filled with guidelines about how to improve error messages: ``Defensive Design for the Web: How to improve error messages, help, forms, and other crisis points'' by Linderman and Fried. Unfortunately, I cannot access it
