### ISSUE TITLE
Technology Research

### ISSUE THREAD

**Issue by kerstinandree** [bptlab/fCM-design-support#16]
We need to find out which technologies exist and which we want to use.

- [ ] Collect different technologies we want to explore
- [ ] Collect Advantages/Disadvantages of each technology
- [ ] Decide on technologies we want to use

**Comment by LeonBein** [comment]
This might be an interesting overview over js modeling libs, especially for UML and OCL:
https://modeling-languages.com/javascript-drawing-libraries-diagrams/
