### ISSUE TITLE
Model data model by hand

### ISSUE THREAD

**Issue by ma-ro** [bptlab/fCM-design-support#27]
As a user, I want to model my data model by hand. 

- [x] model data model by hand
- [x] can create data classes, associations, and attributes
- [x] add associations to schema
- [x] check associations labels
- [x] check attributes labels
- [x] remove arrow head
- [x] associations have cardinality constraints
- [x] associations have goal cardinality constraints (which are not shown if they do not deviate from normal cardinality constraints)
- [x] pushed to develop

**Comment by LeonBein** [comment]
Nice to have: Data model can be exported to the uml XML Metadata Interchange (XMI) format for compatibility to other tools.
