### ISSUE TITLE
Guidelines checking

### ISSUE THREAD

**Issue by ma-ro** [bptlab/fCM-design-support#41]
As a user, I want to have the guidelines of the fCM design support team to be checked. Starting with one examples guideline as a reference implementation. The exact guidelines are still to be decided and not part of this issue.

- [ ] example guidelines is choosen
- [ ] guidelines checking is implemented
- [ ] guidelines violations are shown in the error list
- [ ] pushed to develop

**Comment by LeonBein** [comment]
@ma-ro looks done to me with the "meaningful labels" guideline, right?
