### ISSUE TITLE
Think about how to solve/check selected guidelines

### ISSUE THREAD

**Issue by kerstinandree** [bptlab/fCM-design-support#46]
We decided to separate the checks into 4 levels:
https://docs.google.com/document/d/1htn6AMN1ZEHjM8wbKEKFE6Srq_QA6zWyIKQXQY4ESSw/edit?usp=sharing

Details on what and how to check (for each guideline in a huge table) is written down here:
https://docs.google.com/spreadsheets/d/1KSPcRBWMFZ6jpeOx_CtvCb6Kc_V-BQMzqGT43eKqy-c/edit?usp=sharing

**Comment by carlaterboven** [comment]
We decided to separate the checks into 4 levels:
https://docs.google.com/document/d/1htn6AMN1ZEHjM8wbKEKFE6Srq_QA6zWyIKQXQY4ESSw/edit?usp=sharing

Details on what and how to check (for each guideline in a huge table) is written down here:
https://docs.google.com/spreadsheets/d/1KSPcRBWMFZ6jpeOx_CtvCb6Kc_V-BQMzqGT43eKqy-c/edit?usp=sharing

**Comment by LeonBein** [comment]
I assume this to be obsolete [close]
