### ISSUE TITLE
Related Work Research for Levels of Integration

### ISSUE THREAD

**Issue by kerstinandree** [bptlab/fCM-design-support#50]
Find literature for each level. For example, there exist different standard documentation which support modeling at level 1. Also, there are different tools (e.g., bpmn.io or lucid chart, etc.). Find out if they support modeling process on one of the four levels.

Collect you information and write a short paragraph in the wiki (Guidelines Integration page) about the motivation of the levels and related work.

**Comment by LeonBein** [comment]
I assume this to be obsolete [close]
