### ISSUE TITLE
[Consistency - Data Model / OLC] OLC identifier and data classes in data model update each other

### ISSUE THREAD

**Issue by MaximilianKoenig** [bptlab/fCM-design-support#54]
As a user, I want that the OLC identifier and the respective class in the OLC update each other when one of them is changed. This includes that creating a new data class automatically creates a new empty OLC named after the data class and vice versa.

- [x] Creating a new data class creates an empty OLC with the class name as identifier
- [x] Creating a new OLC creates a new data class with the identifier of the OLC as name
- [x] Updating the name of a data class updates the identifier of the respective OLC
- [x] Updating the identifier of an OLC updates the class name in the data model
- [x] pushed to develop

**Comment by LeonBein** [comment]
Done by closing #77
