### ISSUE TITLE
Designate Case Class

### ISSUE THREAD

**Issue by LeonBein** [bptlab/fCM-design-support#80]
As a user, I want to designate a case class 
in order document this domain information 
and to enable more advanced checking 

- [x] DM allows to designate one class as case class
- [x] pushed to develop

**Comment by ma-ro** [comment]
@LeonBein Yes thats absolutely true. Due to our limited timeline, as a first version, I implemented it as a toggle. The next logical step would be, to set the attribute for all other classes on false.
